Create very_basic_agent.py
leagonnet33/RL_project pull request #4
Opened 2022-03-13 14:45 UTC by leagonnet33

implémentation d'un agent extrêmement basique pour me familiariser avec l'environnement 
La logique suivie par cet agent est la suivante:
- si on n'a pas assez d'argent pour acheter, on vend ou on ne fait rien avec proba 0.5
- si on a gagné de l'argent à l'itération précédente (= reward > 1), on achète (ou on ne fait rien avec proba epsilon)
- si on a perdu de l'argent à l'itération précédente (= reward < 1), on vend (ou on ne fait rien avec proba epsilon)

2022-03-13 18:28 UTC, leagonnet33 commented
- Création de la classe de l'agent epsilon greedy et d'une fonction permettant de run cet agent. 

- J'ai également ajouté une ligne dans le fichier portfolio car la quantité de cash dans le portefeuille ne se mettait pas à jour quand on faisait un achat

- J'ai géré directement dans la fonction agent_step() les cas où: pas assez de cash pour acheter, ou pas de crypto à vendre. J'ai l'impression qu'il y a des lignes dans portfolio.py qui sont censées gérer ces cas, mais sans ajouter la disjonction de cas dans agent_step() je me retrouvais avec des runs où l'action prise était systématiquement de vendre et on était juste toujours à 0 coin du coup

2022-03-18 19:11 UTC, Bassvelitchkine requested changes
Je t'ai fait des remarques un peu spécifiques à différents endroits du code, et ici, je liste mes remarques générales :)

Avant tout, je pense qu'il faut revoir l'architecture.

1. Tu as choisi de faire un fichier `e-greedy_agent.py` et un autre `very_basic_agent.py`. Je pense qu'il faut un unique fichier `agents.py` dans lequel sont regroupés tous nos agents, sous forme de classes : le *BaseAgent* que tu as dans `e-greedy_agent.py` tout d'abord, ensuite une classe *DumbAgent* qui reprend ce que tu as fait dans `very_basic_agent.py` et enfin *EpsilonGreedyAgent*.
2. Tout ce qui concerne le run, donc tes fonctions *run_epsilon_greedy_agent* et *run_very_basic_agent* doivent toutes être dans un autre fichier fichier python intitulé `runners.py` ou `trainers.py`. Il y a d'ailleurs sans doute moyen de faire de ces deux fonctions une unique fonction avec les bons paramètres.
3. Il faudrait enfin un dernier fichier `main.py` ou `app.py` dans lequel on fait tourner nos différents agents dans leur environnement. C'est dans ce fichier qu'on instancie les différents objets et qu'on les fait passer dans leurs "trainers".

2022-03-18 19:11 UTC, bvelitchkine commented on portfolio.py
> +
Je suis d'accord avec les changements effectués, mais il faut initialiser ```self.portfolio_cash_``` différemment, car pour le moment, c'est initialisé à 0, et nous ce qu'on voudrait, c'est que ce soit initialisé à par exemple 10k€, et que ça baisse à mesure qu'on achète des cryptos, que ça augmente à mesure qu'on en vend.

2022-03-18 19:11 UTC, bvelitchkine commented on very_basic_agent.py
> +    METRICS = ["open", "high", "low", "close", "volume ETH", "volume USDT", "tradecount"]
On utilise en général cette notation pour des variables globales, définies hors des fonctions, comme dans le fichier `portfolio.py` par exemple.

2022-03-18 19:11 UTC, bvelitchkine commented on very_basic_agent.py
> +                else: action = 0
Toute cette partie "prise de décision" devrait aller dans la classe *DumbAgent* que je mentionne dans mes remarques générales.

2022-03-18 19:11 UTC, bvelitchkine commented on e-greedy_agent.py
> +    agent = EpsilonGreedyAgent()
- **METRICS** hors de la fonction car plutôt une variable globale.
- Instanciation des différents objets dans un fichier `main.py` ou `app.py` cf. remarques générales de cette review.

2022-03-18 19:11 UTC, bvelitchkine commented on e-greedy_agent.py
> +            else: current_action = 1
Effectivement, cette partie disjonction de cas que tu mentionnes dans tes commentaires est déjà prévues dans la méthode *apply_action* de *Portfolio*. Alors il y a peut-être une erreur dans le code, mais je pense qu'il doit se régler du côté de `portfolio.py` plutôt qu'ici si possible.

2022-03-21 09:47 UTC, closed without merging

2022-03-21 09:47 UTC, leagonnet33 commented
Outdated -> je ferme